x-local-logging: &local-logging
  driver: local

services:
  zookeeper:
    logging: *local-logging
    image: ${ZOOKEEPER_IMAGE_NAME}
    restart: unless-stopped
    volumes:
      - zoo-data:/var/lib/zookeeper/data
      - zoo-log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    logging: *local-logging
    image: ${KAFKA_IMAGE_NAME}
    restart: unless-stopped
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_BROKER_ID: 1
      KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES: 268435456
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LOG_SEGMENT_BYTES: 268435456
      KAFKA_MESSAGE_MAX_BYTES: 268435456
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PRODUCER_MAX_REQUEST_SIZE: 268435456
      KAFKA_REPLICA_FETCH_MAX_BYTES: 268435456
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  redis:
    logging: *local-logging
    image: ${REDIS_IMAGE_NAME}
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    command:
      - redis-server
      - --save
      - "60"
      - "1"
      - --loglevel
      - warning

  postgres:
    logging: *local-logging
    image: ${POSTGRES_IMAGE_NAME}
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/migrations/init.sql:/root/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  clickhouse:
    logging: *local-logging
    image: ${CLICKHOUSE_IMAGE_NAME}
    restart: unless-stopped
    volumes:
      - ./docker/config.xml:/etc/clickhouse-server/config.d/highlight.xml:ro
      - ./docker/users.xml:/etc/clickhouse-server/users.d/highlight.xml:ro
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server

  collector:
    logging: *local-logging
    restart: unless-stopped
    build:
      dockerfile: ./docker/collector.Dockerfile
      pull: true
      target: collector
      context: .
      args:
        - IN_DOCKER_GO
        - SSL
        - OTEL_COLLECTOR_BUILD_IMAGE_NAME
        - OTEL_COLLECTOR_IMAGE_NAME
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./backend/localhostssl/server.crt:/server.crt:ro
      - ./backend/localhostssl/server.key:/server.key:ro
    ports:
      - "14318:4318"
    env_file:
      - .env

  predictions:
    logging: *local-logging
    restart: unless-stopped
    build:
      dockerfile: ./packages/predictions/predictions.Dockerfile
      context: .
    env_file:
      - .env

  backend:
    logging: *local-logging
    image: ${BACKEND_IMAGE_NAME}
    restart: unless-stopped
    ports:
      - "13112:8082"
    volumes:
      - highlight-data:/highlight-data
      - ./backend/env.enc:/build/env.enc:ro
      - ./backend/env.enc.dgst:/build/env.enc.dgst:ro
      - ./backend/localhostssl/server.key:/build/localhostssl/server.key:ro
      - ./backend/localhostssl/server.crt:/build/localhostssl/server.crt:ro
    env_file:
      - .env

  frontend:
    logging: *local-logging
    image: ${FRONTEND_IMAGE_NAME}
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./backend/localhostssl/server.key:/etc/ssl/private/ssl-cert.key:ro
      - ./backend/localhostssl/server.pem:/etc/ssl/certs/ssl-cert.pem:ro
    ports:
      - "13110:3000"
    env_file:
      - .env

volumes:
  postgres-data:
  clickhouse-data:
  clickhouse-logs:
  redis-data:
  kafka-data:
  zoo-log:
  zoo-data:
  highlight-data: